// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/criar-conta": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/home/criar-rotina": {
    params: {};
  };
  "/home/configuracoes": {
    params: {};
  };
  "/home/buscar": {
    params: {};
  };
  "/home/adicionar-tarefa": {
    params: {};
  };
  "/home/adicionar-categoria": {
    params: {};
  };
  "/home/renomear/:id": {
    params: {
      "id": string;
    };
  };
  "/home/detalhes/:id": {
    params: {
      "id": string;
    };
  };
  "/home/rascunhos": {
    params: {};
  };
  "/home/rascunhos/renomear/:id": {
    params: {
      "id": string;
    };
  };
  "/home/rascunhos/detalhes-tarefa/:id": {
    params: {
      "id": string;
    };
  };
  "/home/rascunhos/detalhes-categoria/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/criar-conta" | "/login" | "/home" | "/home/criar-rotina" | "/home/configuracoes" | "/home/buscar" | "/home/adicionar-tarefa" | "/home/adicionar-categoria" | "/home/renomear/:id" | "/home/detalhes/:id" | "/home/rascunhos" | "/home/rascunhos/renomear/:id" | "/home/rascunhos/detalhes-tarefa/:id" | "/home/rascunhos/detalhes-categoria/:id";
  };
  "./layout/LayoutRegister/layout.tsx": {
    id: "layout/LayoutRegister/layout";
    page: "/criar-conta" | "/login";
  };
  "./pages/CriarConta/component.tsx": {
    id: "pages/CriarConta/component";
    page: "/criar-conta";
  };
  "./pages/Login/component.tsx": {
    id: "pages/Login/component";
    page: "/login";
  };
  "./layout/LayoutHome/layout.tsx": {
    id: "layout/LayoutHome/layout";
    page: "/home" | "/home/criar-rotina" | "/home/configuracoes" | "/home/buscar" | "/home/adicionar-tarefa" | "/home/adicionar-categoria" | "/home/renomear/:id" | "/home/detalhes/:id" | "/home/rascunhos" | "/home/rascunhos/renomear/:id" | "/home/rascunhos/detalhes-tarefa/:id" | "/home/rascunhos/detalhes-categoria/:id";
  };
  "./pages/Tasks/component.tsx": {
    id: "pages/Tasks/component";
    page: "/home" | "/home/criar-rotina" | "/home/configuracoes" | "/home/buscar" | "/home/adicionar-tarefa" | "/home/adicionar-categoria" | "/home/renomear/:id" | "/home/detalhes/:id" | "/home/rascunhos" | "/home/rascunhos/renomear/:id" | "/home/rascunhos/detalhes-tarefa/:id" | "/home/rascunhos/detalhes-categoria/:id";
  };
  "./pages/CreateRotina/component.tsx": {
    id: "pages/CreateRotina/component";
    page: "/home/criar-rotina";
  };
  "./pages/Configuracao/component.tsx": {
    id: "pages/Configuracao/component";
    page: "/home/configuracoes";
  };
  "./pages/SearchTasks/component.tsx": {
    id: "pages/SearchTasks/component";
    page: "/home/buscar";
  };
  "./pages/AdicionarTarefa/component.tsx": {
    id: "pages/AdicionarTarefa/component";
    page: "/home/adicionar-tarefa";
  };
  "./pages/AdicionarCategoria/component.tsx": {
    id: "pages/AdicionarCategoria/component";
    page: "/home/adicionar-categoria";
  };
  "./modais/Renomear-tarefa/component.tsx": {
    id: "renomear-home";
    page: "/home/renomear/:id";
  };
  "./modais/Detalhes-tarefa/component.tsx": {
    id: "detalhes-rotina";
    page: "/home/detalhes/:id";
  } | {
    id: "detalhes-rascunhos";
    page: "/home/rascunhos/detalhes-tarefa/:id";
  };
  "./pages/rascunhos/component.tsx": {
    id: "pages/rascunhos/component";
    page: "/home/rascunhos" | "/home/rascunhos/renomear/:id" | "/home/rascunhos/detalhes-tarefa/:id" | "/home/rascunhos/detalhes-categoria/:id";
  };
  "./modais/Renomear-categoria-task-rascunho/component.tsx": {
    id: "renomear-rascunhos";
    page: "/home/rascunhos/renomear/:id";
  };
  "./modais/Detalhes-categoria/component.tsx": {
    id: "detalhes-categoria";
    page: "/home/rascunhos/detalhes-categoria/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout/LayoutRegister/layout": typeof import("./app/./layout/LayoutRegister/layout.tsx");
  "pages/CriarConta/component": typeof import("./app/./pages/CriarConta/component.tsx");
  "pages/Login/component": typeof import("./app/./pages/Login/component.tsx");
  "layout/LayoutHome/layout": typeof import("./app/./layout/LayoutHome/layout.tsx");
  "pages/Tasks/component": typeof import("./app/./pages/Tasks/component.tsx");
  "pages/CreateRotina/component": typeof import("./app/./pages/CreateRotina/component.tsx");
  "pages/Configuracao/component": typeof import("./app/./pages/Configuracao/component.tsx");
  "pages/SearchTasks/component": typeof import("./app/./pages/SearchTasks/component.tsx");
  "pages/AdicionarTarefa/component": typeof import("./app/./pages/AdicionarTarefa/component.tsx");
  "pages/AdicionarCategoria/component": typeof import("./app/./pages/AdicionarCategoria/component.tsx");
  "renomear-home": typeof import("./app/./modais/Renomear-tarefa/component.tsx");
  "detalhes-rotina": typeof import("./app/./modais/Detalhes-tarefa/component.tsx");
  "pages/rascunhos/component": typeof import("./app/./pages/rascunhos/component.tsx");
  "renomear-rascunhos": typeof import("./app/./modais/Renomear-categoria-task-rascunho/component.tsx");
  "detalhes-rascunhos": typeof import("./app/./modais/Detalhes-tarefa/component.tsx");
  "detalhes-categoria": typeof import("./app/./modais/Detalhes-categoria/component.tsx");
};