// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/criar-conta": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/home/criar-rotina": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/criar-conta" | "/login" | "/home" | "/home/criar-rotina";
  };
  "./layout/LayoutRegister/layout.tsx": {
    id: "layout/LayoutRegister/layout";
    page: "/criar-conta" | "/login";
  };
  "./pages/CriarConta/component.tsx": {
    id: "pages/CriarConta/component";
    page: "/criar-conta";
  };
  "./pages/Login/component.tsx": {
    id: "pages/Login/component";
    page: "/login";
  };
  "./layout/LayoutHome/layout.tsx": {
    id: "layout/LayoutHome/layout";
    page: "/home" | "/home/criar-rotina";
  };
  "./pages/Tasks/component.tsx": {
    id: "pages/Tasks/component";
    page: "/home" | "/home/criar-rotina";
  };
  "./pages/CreateRotina/component.tsx": {
    id: "pages/CreateRotina/component";
    page: "/home/criar-rotina";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layout/LayoutRegister/layout": typeof import("./app/./layout/LayoutRegister/layout.tsx");
  "pages/CriarConta/component": typeof import("./app/./pages/CriarConta/component.tsx");
  "pages/Login/component": typeof import("./app/./pages/Login/component.tsx");
  "layout/LayoutHome/layout": typeof import("./app/./layout/LayoutHome/layout.tsx");
  "pages/Tasks/component": typeof import("./app/./pages/Tasks/component.tsx");
  "pages/CreateRotina/component": typeof import("./app/./pages/CreateRotina/component.tsx");
};